apiVersion: v1
kind: Pod
metadata:
  name: photo-stock
  labels:  
    app: photo-stock
spec:
  containers:
    - name: photo-stock
      image: "gaps-apps.ru:442/photo_stock:latest"
      env:
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: photo-stock
              key: BOT_TOKEN
              optional: false
