# Generated by Django 4.0.3 on 2022-03-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_data', models.BinaryField()),
                ('description', models.TextField(default='')),
                ('base64', models.TextField(null=True)),
            ],
            options={
                'db_table': 'photos',
                'managed': True,
            },
        ),
    ]
